const types = {
  LIST_ID: "LIST_ID",
  PLACE_ID: "PLACE_ID",
  NAME: "NAME",
  DESCRIPTION: "DESCRIPTION",
  DATE_START_MISSING: "DATE_START_MISSING",
  DATE_END_MISSING: "DATE_END_MISSING",
  DATE_START: "DATE_START",
  DATE_END: "DATE_END",
  DATE_ORDER: "DATE_ORDER",
};

module.exports = types;
